# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'AlzAppV2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlzAppV2
  pod 'FDSoundActivatedRecorder'

end
